
const GENERIC_ERROR = 500
const PAGE_NOT_FOUND = 404
const BOOKID_NOT_FOUND = 404
const EMPTY_REQUEST_BODY = 400
const READ_PAGE_MORE_THAN_COUNTED = 400
const SUCCESS_INPUT_BOOK = 201
const SUCCESS = 200

module.exports = { GENERIC_ERROR, PAGE_NOT_FOUND, BOOKID_NOT_FOUND, EMPTY_REQUEST_BODY, READ_PAGE_MORE_THAN_COUNTED, SUCCESS_INPUT_BOOK, SUCCESS }
